name: Nexus Mods

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release:
    name: Release (${{matrix.config.mod_game_id}})
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        config:
          - { mod_game_id: 'CK2',     nexus_game_id: 'crusaderkings2',  nexus_mod_id: '70', mod_file_name: 'more-cultural-names'      }
          - { mod_game_id: 'CK2HIP',  nexus_game_id: 'crusaderkings2',  nexus_mod_id: '71', mod_file_name: 'hip-more-cultural-names'  }
          - { mod_game_id: 'CK3',     nexus_game_id: 'crusaderkings3',  nexus_mod_id: '11', mod_file_name: 'more-cultural-names'      }
          - { mod_game_id: 'CK3AE',   nexus_game_id: 'crusaderkings3',  nexus_mod_id: '30', mod_file_name: 'ae-more-cultural-names'   }
          - { mod_game_id: 'CK3CE',   nexus_game_id: 'crusaderkings3',  nexus_mod_id: '31', mod_file_name: 'ce-more-cultural-names'   }
          - { mod_game_id: 'CK3CMH',  nexus_game_id: 'crusaderkings3',  nexus_mod_id: '20', mod_file_name: 'cmh-more-cultural-names'  }
          - { mod_game_id: 'CK3IBL',  nexus_game_id: 'crusaderkings3',  nexus_mod_id: '12', mod_file_name: 'ibl-more-cultural-names'  }
          - { mod_game_id: 'CK3MBP',  nexus_game_id: 'crusaderkings3',  nexus_mod_id: '19', mod_file_name: 'mbp-more-cultural-names'  }
          - { mod_game_id: 'CK3SoW',  nexus_game_id: 'crusaderkings3',  nexus_mod_id: '24', mod_file_name: 'sow-more-cultural-names'  }
          - { mod_game_id: 'CK3TBA',  nexus_game_id: 'crusaderkings3',  nexus_mod_id: '29', mod_file_name: 'tba-more-cultural-names'  }
          - { mod_game_id: 'CK3TFE',  nexus_game_id: 'crusaderkings3',  nexus_mod_id: '22', mod_file_name: 'tfe-more-cultural-names'  }
          - { mod_game_id: 'HOI4',    nexus_game_id: 'heartsofironiv',  nexus_mod_id: '22', mod_file_name: 'more-cultural-names'      }
          - { mod_game_id: 'HOI4MDM', nexus_game_id: 'heartsofironiv',  nexus_mod_id: '35', mod_file_name: 'mdm-more-cultural-names'  }
          - { mod_game_id: 'HOI4TGW', nexus_game_id: 'heartsofironiv',  nexus_mod_id: '32', mod_file_name: 'tgw-more-cultural-names'  }

    steps:
    - name: Prepare
      run: wget "https://github.com/hmlendea/more-cultural-names/releases/download/${{github.ref_name}}/mcn_${{matrix.config.mod_game_id}}_${GITHUB_REF:11}.zip" -O "${{matrix.config.mod_game_id}}.zip"

    - name: Upload
      uses: greatness7/nexusmods_file_updater@v2
      with:
        username: ${{secrets.NEXUS_USERNAME}}
        password: ${{secrets.NEXUS_PASSWORD}}
        game_domain_name: ${{matrix.config.nexus_game_id}}
        mod_id: ${{matrix.config.nexus_mod_id}}
        file_name: ${{matrix.config.mod_file_name}}
        file_version: ${{github.ref_name}}
        update_version: true
        new_existing_version: true
        original_file: "${{matrix.config.mod_file_name}}.*"
        file_description: "Changelog: https://github.com/hmlendea/more-cultural-names/releases/${{github.ref_name}}"
        file_path: "${{matrix.config.mod_game_id}}.zip"